apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-w3hz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-w3hz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-w3hz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-w3hz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-w3hz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qomq-tenant/rhtap-demo-app/hacbs-test-project-w3hz@sha256:d07adc5f6effc9b4de18d9adcde2509239c0e647d5f9052a0f75d6b0b4ac828b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
