apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-w3hz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qomq-tenant/rhtap-demo-app/hacbs-test-project-w3hz@sha256:1fabba704efa4f91ceee4b60a4e62d54e5035d936f1956f313073b2e57c0d915
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
