apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-w3hz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qomq-tenant/rhtap-demo-app/hacbs-test-project-w3hz@sha256:d07adc5f6effc9b4de18d9adcde2509239c0e647d5f9052a0f75d6b0b4ac828b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
